defaults: &defaults
  secret_key_base: "*!#JLQ W*JAS'DJAS*!H#UHDAS'hK!&*HJKBN'JSANJHSAHuih12euihuhukqnd,i hO*!#HONlwijQI JOI!# @L*$U !"
  ga:
    account: 'UA-Something'
    domain: 'localhost'
  s3:
    bucket: 'My-bucket'
    access_key: 'access_key'
    secret_key: 'secret_key'
  database:
    name: "blog"
    username: "blog"
    password: "dev-blog-123"

  meta:
    title: "pothibo's blog"
    author: 'https://google.com/+PierOlivierThibault'
    description: 'Ruby, Javascript, CSS blog. I use my experience to help you understand different programming concepts.'

  theme: "default"


development:
  <<: *defaults

test:
  <<: *defaults
  name: "blog-test"

production:
  <<: *defaults
  
